### ISSUE TITLE
Startet nicht auf Windows

### ISSUE THREAD

**Issue by 0xhtml** [CAU-Kiel-Tech-Inf/socha-gui#13]
Auf Windows 10 mit Java 1.8.0_192 startet das Programm nicht.
Es gibt den Fehler

	[14:17:51.593] Server stderr: java.lang.UnsupportedClassVersionError: sc/server/Application has been compiled by a more recent version of the Java Runtime (class file version 54.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	[14:17:51.595] Server stderr:
	        at java.lang.ClassLoader.defineClass1(Native Method)
	        at java.lang.ClassLoader.defineClass(Unknown Source)
	        at java.security.SecureClassLoader.defineClass(Unknown Source)
	        at java.net.URLClassLoader.defineClass(Unknown Source)
	        at java.net.URLClassLoader.access$100(Unknown Source)
	        at java.net.URLClassLoader$1.run(Unknown Source)
	        at java.net.URLClassLoader$1.run(Unknown Source)
	        at java.security.AccessController.doPrivileged(Native Method)
	        at java.net.URLClassLoader.findClass(Unknown Source)
	        at java.lang.ClassLoader.loadClass(Unknown Source)
	        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	        at java.lang.ClassLoader.loadClass(Unknown Source)
	        at sun.launcher.LauncherHelper.checkAndLoadMain(Unknown Source)

	[14:17:51.596] Server stderr: Error: A JNI error has occurred, please check your installation and try again

	[14:17:51.598] Server stderr: Exception in thread "main"

aus.

**Comment by soerendomroes** [comment]
Tritt bei mir auch auf, mit Windows 10, und Java 1.8.0_121

**Comment by xeruf** [comment]
Scheint ein Problem seitens Travis CI zu sein. Ich schau mal nach.

**Comment by xeruf** [comment]
So, hab den Release neu gemacht, jetzt sollte alles gehen. Danke fürs melden :)
